### ISSUE TITLE
runfiles_test is failing with Bazel@HEAD in CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_dotnet#393]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#018b3b61-bcaf-4cb7-a81f-2f4a9710f5c0

Platform : MacOS, Windows, Ubuntu

Logs:
```
//dotnet/private/tests/runfiles:runfiles_test                            FAILED in 3 out of 3 in 0.4s
```

Steps:
```
git clone https://github.com/bazelbuild/rules_dotnet.git
git reset 03ac96aac3b8a3cfc28830b317f72a33e74e6949 --hard
export USE_BAZEL_VERSION=2ddacab80af1dca3c04e74809827c47ec4bc8498
bazel build //...
```

CC Greenteam @fweikert

**Comment by sgowroji** [comment]
Hi @tomaszstrejczek / @purkhusid, Can you take a look?

**Comment by purkhusid** [comment]
Yes, I'm in the process of making the rules work with bzlmod. I'll disable bzlmod in CI until I'm done.

**Comment by purkhusid** [comment]
bzlmod has been disabled in CI so this should be fixed for the Bazel@HEAD build

**Comment by sgowroji** [comment]
Hi @purkhusid, We are still seeing the above failure in Windows CI. Can you have a look https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3421#018b792b-ba8c-4407-bb53-3dad0d633c00

**Comment by purkhusid** [comment]
Was missing `--noenable_bzlmod` on the windows build. Should be fixed on master now.

**Comment by sgowroji** [comment]
Thanks for the Quick update and fix. It shows green now.
